---
name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  integration:
    name: Run the integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Setup Poetry
        run: pipx install poetry
      - name: Run tests
        run: |
          poetry install
          poetry run pytest -vv
